import {FormEvent,useEffect,useState} from 'react';
import {api,Project,Suite,Bug,Run} from './api';

type View='dashboard'|'projects'|'bugs';
function App(){
 const [token,setToken]=useState(localStorage.getItem('qa_token')); const [view,setView]=useState<View>('dashboard'); const [projects,setProjects]=useState<Project[]>([]); const [selected,setSelected]=useState<Project|null>(null);
 const [stats,setStats]=useState<Record<string,number>>({}); const [error,setError]=useState('');
 const refresh=async()=>{try{const [p,d]=await Promise.all([api.projects(),api.dashboard()]);setProjects(p);setStats(d); if(selected)setSelected(p.find(x=>x.id===selected.id)||null);}catch(e){setError((e as Error).message)}};
 useEffect(()=>{if(token)refresh()},[token]);
 if(!token)return <Login onLogin={(t)=>{localStorage.setItem('qa_token',t);setToken(t)}}/>;
 return <div className="app"><aside><div className="brand">QA<span>Cloud</span></div><button onClick={()=>setView('dashboard')}>Dashboard</button><button onClick={()=>setView('projects')}>Projects</button><button onClick={()=>setView('bugs')}>Defects</button><button className="logout" onClick={()=>{localStorage.removeItem('qa_token');setToken(null)}}>Sign out</button></aside><main><header><div><p className="eyebrow">QUALITY ENGINEERING</p><h1>{view==='dashboard'?'QA Dashboard':view==='projects'?'Projects':'Defect Tracker'}</h1></div><button className="secondary" onClick={refresh}>Refresh</button></header>{error&&<div className="error">{error}</div>}{view==='dashboard'&&<Dashboard stats={stats} projects={projects} onSelect={(p)=>{setSelected(p);setView('projects')}}/>}{view==='projects'&&<Projects projects={projects} selected={selected} refresh={refresh} onSelect={setSelected}/>} {view==='bugs'&&<Bugs projects={projects}/>}</main></div>
}
function Login({onLogin}:{onLogin:(token:string)=>void}){const [email,setEmail]=useState('demo@qacloud.local');const [password,setPassword]=useState('ChangeMe123!');const [error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{const r=await api.login(email,password);onLogin(r.token)}catch(err){setError((err as Error).message)}};return <div className="login"><div className="login-card"><div className="brand big">QA<span>Cloud</span></div><p className="muted">Cloud-based QA & test management platform</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button className="primary">Sign in</button></form><p className="hint">Demo: demo@qacloud.local / ChangeMe123!</p></div></div>}
function Dashboard({stats,projects,onSelect}:{stats:Record<string,number>;projects:Project[];onSelect:(p:Project)=>void}){return <><div className="grid four"><Stat label="Projects" value={stats.projects??0}/><Stat label="Test Cases" value={stats.testCases??0}/><Stat label="Failed Runs" value={stats.failedRuns??0}/><Stat label="Open Defects" value={stats.openBugs??0}/></div><section><div className="section-head"><h2>Projects</h2><span>{projects.length} total</span></div><div className="cards">{projects.map(p=><button className="project-card" key={p.id} onClick={()=>onSelect(p)}><div className="project-icon">P</div><div><strong>{p.name}</strong><p>{p.description}</p></div></button>)}</div></section></>}
function Stat({label,value}:{label:string;value:number}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
function Projects({projects,selected,refresh,onSelect}:{projects:Project[];selected:Project|null;refresh:()=>void;onSelect:(p:Project)=>void}){const [name,setName]=useState('');const [description,setDescription]=useState('');const create=async()=>{if(!name.trim())return;await api.createProject(name,description);setName('');setDescription('');await refresh()}; return <div className="content-grid"><section><div className="section-head"><h2>Project list</h2></div>{projects.map(p=><button className={`list-row ${selected?.id===p.id?'active':''}`} key={p.id} onClick={()=>onSelect(p)}><span>{p.name}</span><small>{p.description}</small></button>)}<div className="form-box"><h3>Create project</h3><input placeholder="Project name" value={name} onChange={e=>setName(e.target.value)}/><textarea placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)}/><button className="primary" onClick={create}>Create project</button></div></section>{selected?<ProjectDetail project={selected}/>:<section className="empty"><h2>Select a project</h2><p>Choose a project to manage suites, cases, runs and defects.</p></section>}</div>}
function ProjectDetail({project}:{project:Project}){const [suites,setSuites]=useState<Suite[]>([]);const [runs,setRuns]=useState<Run[]>([]);const [bugs,setBugs]=useState<Bug[]>([]);const [newSuite,setNewSuite]=useState('');const load=async()=>{const [s,r,b]=await Promise.all([api.suites(project.id),api.runs(project.id),api.bugs(project.id)]);setSuites(s);setRuns(r);setBugs(b)};useEffect(()=>{load()},[project.id]);const createSuite=async()=>{if(!newSuite.trim())return;await api.createSuite(project.id,newSuite,'QA test suite');setNewSuite('');load()};const run=async()=>{await api.startRun(project.id);setTimeout(load,800)};return <section><div className="section-head"><div><h2>{project.name}</h2><p>{project.description}</p></div><button className="primary" onClick={run}>Run tests</button></div><div className="tabs"><span>Suites & Cases</span><span>Runs</span><span>Defects</span></div><div className="form-inline"><input placeholder="New test suite" value={newSuite} onChange={e=>setNewSuite(e.target.value)}/><button className="secondary" onClick={createSuite}>Add suite</button></div>{suites.map(s=><SuiteCard key={s.id} suite={s}/>) }<div className="run-list"><h3>Recent test runs</h3>{runs.length===0?<p className="muted">No runs yet.</p>:runs.map(r=><div className="run-row" key={r.id}><span>Run #{r.id}</span><b className={r.status.toLowerCase()}>{r.status}</b><small>{r.passed}/{r.total} passed</small></div>)}</div><div className="run-list"><h3>Defects</h3>{bugs.length===0?<p className="muted">No defects.</p>:bugs.slice(0,5).map(b=><div className="run-row" key={b.id}><span>{b.title}</span><b>{b.severity}</b><small>{b.status}</small></div>)}</div></section>}
function SuiteCard({suite}:{suite:Suite}){const [cases,setCases]=useState<any[]>([]);useEffect(()=>{api.cases(suite.id).then(setCases)},[suite.id]);return <div className="suite"><div><strong>{suite.name}</strong><p>{suite.description}</p></div><div>{cases.map(c=><div className="case-row" key={c.id}><span>{c.title}</span><small>{c.priority}</small></div>)}</div></div>}
function Bugs({projects}:{projects:Project[]}){const [project,setProject]=useState(projects[0]?.id||0);const [bugs,setBugs]=useState<Bug[]>([]);const [title,setTitle]=useState('');const load=()=>{if(project)api.bugs(project).then(setBugs)};useEffect(load,[project,projects]);const create=async()=>{if(!title.trim())return;await api.createBug(project,{title,description:'Created from defect tracker',severity:'MEDIUM'});setTitle('');load()};return <section><div className="form-inline"><select value={project} onChange={e=>setProject(Number(e.target.value))}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input placeholder="New defect title" value={title} onChange={e=>setTitle(e.target.value)}/><button className="primary" onClick={create}>Create defect</button></div>{bugs.map(b=><div className="bug-card" key={b.id}><div><strong>{b.title}</strong><p>{b.description}</p></div><div className="bug-meta"><b>{b.severity}</b><span>{b.status}</span></div></div>)}</section>}
export default App;
